/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.paciente;

import datos.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Gestion;
import presentacion.medico.RegistrarMedico;
public class RegistrarPaciente extends javax.swing.JDialog {

    /**
     * Creates new form RegistrarPaciente
     */
    public RegistrarPaciente(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbIdentidad = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cmbSangre = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR PACIENTE");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setText("TIPO IDENTIDAD:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 99, 31);

        cmbIdentidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "C.C", "T.I", " " }));
        getContentPane().add(cmbIdentidad);
        cmbIdentidad.setBounds(110, 20, 130, 30);

        jLabel2.setText("IDENTIDAD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 30, 80, 20);

        txtIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdentidad);
        txtIdentidad.setBounds(350, 20, 110, 30);

        jLabel3.setText("NOMBRE:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 50, 70, 30);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(110, 50, 130, 30);

        jLabel4.setText("APELLIDO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 60, 70, 20);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(350, 50, 110, 30);

        jLabel5.setText("EDAD:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 90, 40, 20);

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(110, 80, 130, 30);

        jLabel6.setText("TIPO SANGRE:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(260, 90, 90, 20);

        cmbSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "O+", "O-", "AB+", "AB-", "A-", "A+", "B-", "B+", " " }));
        getContentPane().add(cmbSangre);
        cmbSangre.setBounds(350, 80, 110, 30);

        jLabel7.setText("TELEFONO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 110, 70, 30);

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(110, 110, 130, 30);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(480, 130, 100, 30);

        setSize(new java.awt.Dimension(818, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (this.verificarmedico() == true) {
            JOptionPane.showMessageDialog(null, "No hay médicos registrados", "Registro de Paciente", JOptionPane.ERROR_MESSAGE);
            this.dispose();
           RegistrarMedico rm = new RegistrarMedico(new javax.swing.JDialog(), true);
           rm.setVisible(true);
        }
    }//GEN-LAST:event_formWindowOpened

    private void txtIdentidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentidadKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
       if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
       if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyTyped
        char validar = evt.getKeyChar();
        if (validar < '0' || validar > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_txtIdentidadKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar != 'ñ') && (validar != 'Ñ') && (validar != ' ')) {
            evt.consume();

        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar != 'ñ') && (validar != 'Ñ') && (validar != ' ')) {
            evt.consume();

        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char validar = evt.getKeyChar();
        if (validar < '0' || validar > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char validar = evt.getKeyChar();
        if (validar < '0' || validar > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

   
//        private void buscarPaciente(){
//
//        for (Paciente paciente : ArchivoBinario.leerDatosPa()) {
//            if (txtIdentidad.getText().equals(paciente.getIdentidad())) {
//                try {
//                    cmbIdentidad.setSelectedItem(paciente.getTipoIdentidad());
//                    txtIdentidad.setText(paciente.getIdentidad());
//                    txtNombre.setText(paciente.getNombre());
//                    txtApellido.setText(paciente.getApellido());
//                    txtEdad.setText(paciente.getEdad());
//                    cmbSangre.setSelectedItem(paciente.getTipoSangre());
//                    txtTelefono.setText(paciente.getTelefono());
//                    
//                    
//
//                } catch (Exception ex) {
//                    
//                }
//                
//            }else{
//                JOptionPane.showMessageDialog(null, "No existe esa identidad", "BUSCAR", JOptionPane.ERROR_MESSAGE);
//                limpiar();
//                
//            }
//        }
//
//    }
    public boolean verificarmedico() {
        int cont = 0;
        for (Medico medico: ArchivoBinario.leerDatos()) {
            if (medico != null) {
                cont++;
            }
        }
        if (cont == 0) {
            return true;
        } else {
            return false;
        }
    }
    private void agregar(){
        String mensaje;
        mensaje= Gestion.agregarPacientes(cmbIdentidad.getSelectedItem().toString(), txtIdentidad.getText().trim(), txtNombre.getText().trim(), txtApellido.getText().trim(), 
        txtEdad.getText().trim(),cmbSangre.getSelectedItem().toString(), txtTelefono.getText().trim());
        JOptionPane.showMessageDialog(this, mensaje);
        limpiar();
//        cargarDatos();
    }
    
//    private void modificar(){
//        
//        Gestion.ModificarPacientes(cmbIdentidad.getSelectedItem().toString(), txtIdentidad.getText().trim(), txtNombre.getText().trim(), txtApellido.getText().trim(), 
//        txtEdad.getText().trim(),cmbSangre.getSelectedItem().toString(), txtTelefono.getText().trim(), tblPacientes.getSelectedRow());
//        JOptionPane.showMessageDialog(this, "MODIFICADO CON ÉXITO");
//        limpiar();
//        cargarDatos();
//    }
//    private void eliminar(){
//        Gestion.eliminarPacientes(tblPacientes.getSelectedRow());
//        JOptionPane.showMessageDialog(this, "ELIMINDADO CORRECTAMENTE");
//        limpiar();
//        cargarDatos();
//    }
    
//    private void verDatos(){
//        cmbIdentidad.setSelectedItem(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 0).toString());
//        txtIdentidad.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 1).toString());
//        txtNombre.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 2).toString());
//        txtApellido.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 3).toString());
//        txtEdad.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 4).toString());
//        cmbSangre.setSelectedItem(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 5).toString());
//        txtTelefono.setText(tblPacientes.getValueAt(tblPacientes.getSelectedRow(), 6).toString());
//        
//        cmbIdentidad.requestFocus();
//    }
    
    
    
    private void limpiar(){
        cmbIdentidad.setSelectedItem("SELECCIONE");
        txtIdentidad.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        cmbSangre.setSelectedItem("SELECCIONE");
        txtTelefono.setText("");
        cmbIdentidad.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                RegistrarPaciente dialog = new RegistrarPaciente(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbIdentidad;
    private javax.swing.JComboBox<String> cmbSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
