
package presentacion.medico;

import datos.*;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Gestion;
import presentacion.Menu;
public class RegistrarMedico extends javax.swing.JDialog {

    /**
     * Creates new form RegistrarMedico
     */
    public RegistrarMedico(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtIdentidad = new javax.swing.JTextField();
        cmboSangre = new javax.swing.JComboBox<>();
        txtEspecialidad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmboHorario = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        cmboIdentidad = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR MEDICO");
        getContentPane().setLayout(null);

        jLabel1.setText("TELEFONO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 140, 80, 30);

        jLabel2.setText("TIPO DE SANGRE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 110, 100, 30);

        jLabel3.setText("EDAD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 70, 30);

        jLabel4.setText("APELLIDOS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 50, 70, 30);

        jLabel5.setText("NOMBRES:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 50, 70, 30);

        jLabel6.setText("IDENTIDAD:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 20, 70, 30);

        jLabel7.setText("ESPECIALIDAD:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 80, 90, 30);

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(100, 50, 160, 30);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(360, 50, 170, 30);

        txtEdad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEdadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEdadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEdad);
        txtEdad.setBounds(100, 80, 90, 30);

        txtIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtIdentidad);
        txtIdentidad.setBounds(360, 20, 170, 30);

        cmboSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "O+", "O-", "AB+", "AB-", "A-", "A+", "B-", "B+" }));
        getContentPane().add(cmboSangre);
        cmboSangre.setBounds(90, 110, 170, 30);

        txtEspecialidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEspecialidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEspecialidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtEspecialidad);
        txtEspecialidad.setBounds(360, 80, 150, 30);

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonoKeyTyped(evt);
            }
        });
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(90, 140, 170, 30);

        jLabel8.setText("HORARIO DE ATENCION:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 120, 140, 20);

        cmboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "6:00AM-10:00 AM", "10:00AM-12:00 PM", "2:00PM-6:00PM", " " }));
        getContentPane().add(cmboHorario);
        cmboHorario.setBounds(420, 110, 110, 30);

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(460, 180, 110, 30);

        jLabel9.setText("TIPO IDENTIDAD:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 24, 100, 20);

        cmboIdentidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "C.C", "T.I" }));
        getContentPane().add(cmboIdentidad);
        cmboIdentidad.setBounds(100, 20, 160, 30);

        setSize(new java.awt.Dimension(626, 342));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        agregar();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtIdentidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyPressed
       if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentidadKeyPressed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
       if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtEdadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEdadKeyPressed

    private void txtEspecialidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtEspecialidadKeyPressed

    private void txtTelefonoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtTelefonoKeyPressed

    private void txtIdentidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyTyped
        char validar = evt.getKeyChar();
        if (validar < '0' || validar > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_txtIdentidadKeyTyped

    private void txtApellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyTyped
       char validar = evt.getKeyChar();
        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar != 'ñ') && (validar != 'Ñ') && (validar != ' ')) {
            evt.consume();

        }
    }//GEN-LAST:event_txtApellidoKeyTyped

    private void txtNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyTyped
       char validar = evt.getKeyChar();
        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar != 'ñ') && (validar != 'Ñ') && (validar != ' ')) {
            evt.consume();

        }
    }//GEN-LAST:event_txtNombreKeyTyped

    private void txtEdadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEdadKeyTyped
        char validar = evt.getKeyChar();
        if (validar < '0' || validar > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_txtEdadKeyTyped

    private void txtTelefonoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonoKeyTyped
        char validar = evt.getKeyChar();
        if (validar < '0' || validar > '9') {
            evt.consume();

        }
    }//GEN-LAST:event_txtTelefonoKeyTyped

    private void txtEspecialidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEspecialidadKeyTyped
        char validar = evt.getKeyChar();
        if ((validar < 'a' || validar > 'z') && (validar < 'A' || validar > 'Z') && (validar != 'ñ') && (validar != 'Ñ') && (validar != ' ')) {
            evt.consume();

        }
    }//GEN-LAST:event_txtEspecialidadKeyTyped

     private void agregar() {
        String mensaje;
        mensaje = Gestion.agregarMedicos(cmboIdentidad.getSelectedItem().toString(), txtIdentidad.getText().trim(), txtNombre.getText().trim(), txtApellido.getText().trim(),
                txtEdad.getText().trim(), cmboSangre.getSelectedItem().toString(), txtTelefono.getText().trim(), txtEspecialidad.getText().trim(), cmboHorario.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, mensaje);
        limpiar();

    }


    private void limpiar() {
        cmboIdentidad.setSelectedItem("SELECCIONE");
        txtIdentidad.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        cmboSangre.setSelectedItem("SELECCIONE");
        txtTelefono.setText("");
        txtEspecialidad.setText("");
        cmboHorario.setSelectedItem("SELECCIONE");
        cmboIdentidad.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(RegistrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(RegistrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(RegistrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(RegistrarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                RegistrarMedico dialog = new RegistrarMedico(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmboHorario;
    private javax.swing.JComboBox<String> cmboIdentidad;
    private javax.swing.JComboBox<String> cmboSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
