/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.medico;

import datos.*;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import logica.Gestion;
import presentacion.Menu;
public class VerMedicos extends javax.swing.JDialog {

    
    public VerMedicos(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarDatos();
    }

    private void cargarDatos() {
        tblMedicos.setModel(Gestion.getModeloTablaMedicos());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtIdentidad = new javax.swing.JTextField();
        cmboSangre = new javax.swing.JComboBox<>();
        txtEspecialidad = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cmboHorario = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        cmboIdentidad = new javax.swing.JComboBox<>();
        btnEliminar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("TELEFONO:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 140, 80, 30);

        jLabel2.setText("TIPO DE SANGRE:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 110, 100, 30);

        jLabel3.setText("EDAD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 70, 30);

        jLabel4.setText("APELLIDOS:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 50, 70, 30);

        jLabel5.setText("NOMBRES:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 50, 70, 30);

        jLabel6.setText("IDENTIDAD:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 20, 70, 30);

        jLabel7.setText("ESPECIALIDAD:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(270, 80, 90, 30);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(100, 50, 160, 30);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(360, 50, 170, 30);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(100, 80, 90, 30);
        getContentPane().add(txtIdentidad);
        txtIdentidad.setBounds(360, 20, 170, 30);

        cmboSangre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "O+", "O-" }));
        getContentPane().add(cmboSangre);
        cmboSangre.setBounds(90, 110, 170, 30);
        getContentPane().add(txtEspecialidad);
        txtEspecialidad.setBounds(360, 80, 150, 30);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(90, 140, 170, 30);

        jLabel8.setText("HORARIO DE ATENCION:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(270, 120, 140, 20);

        cmboHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "6:00AM-2:00 PM" }));
        getContentPane().add(cmboHorario);
        cmboHorario.setBounds(420, 110, 110, 30);

        tblMedicos = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblMedicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblMedicos.setFocusable(false);
        tblMedicos.getTableHeader().setReorderingAllowed(false);
        tblMedicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMedicosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMedicos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 240, 570, 190);

        jLabel9.setText("TIPO IDENTIDAD:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 24, 100, 20);

        cmboIdentidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "C.C", "T.I" }));
        getContentPane().add(cmboIdentidad);
        cmboIdentidad.setBounds(100, 20, 160, 30);

        btnEliminar.setText("ELIMINAR");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(460, 180, 90, 30);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(340, 180, 100, 30);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(250, 180, 80, 30);

        setSize(new java.awt.Dimension(640, 535));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblMedicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMedicosMouseClicked
        verDatos();
    }//GEN-LAST:event_tblMedicosMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarMedico();
    }//GEN-LAST:event_btnBuscarActionPerformed

     private void eliminar() {
        Gestion.eliminar(tblMedicos.getSelectedRow());
        JOptionPane.showMessageDialog(this, "ELIMINDADO CORRECTAMENTE");
        limpiar();
        cargarDatos();
    }

    private void modificar() {

        Gestion.modificarMedicos(cmboIdentidad.getSelectedItem().toString(), txtIdentidad.getText().trim(), txtNombre.getText().trim(), txtApellido.getText().trim(),
                txtEdad.getText().trim(), cmboSangre.getSelectedItem().toString(), txtTelefono.getText().trim(), txtEspecialidad.getText().trim(), cmboHorario.getSelectedItem().toString(), tblMedicos.getSelectedRow());
        JOptionPane.showMessageDialog(null, "MODIFICADO CORRECTAMENTE", "MODIFICAR", JOptionPane.ERROR_MESSAGE);
        limpiar();
        cargarDatos();

    }

    private void verDatos() {
        cmboIdentidad.setSelectedItem(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 0).toString());
        txtIdentidad.setText(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 1).toString());
        txtNombre.setText(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 2).toString());
        txtApellido.setText(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 3).toString());
        txtEdad.setText(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 4).toString());
        cmboSangre.setSelectedItem(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 5).toString());
        txtTelefono.setText(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 6).toString());
        txtEspecialidad.setText(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 7).toString());
        cmboHorario.setSelectedItem(tblMedicos.getValueAt(tblMedicos.getSelectedRow(), 8).toString());
        cmboIdentidad.requestFocus();
    }


    private void buscarMedico() {

        for (Medico medico : ArchivoBinario.leerDatos()) {
            if (txtIdentidad.getText().equals(medico.getIdentidad())) {
                try {
                    cmboIdentidad.setSelectedItem(medico.getTipoIdentidad());
                    txtIdentidad.setText(medico.getIdentidad());
                    txtNombre.setText(medico.getNombre());
                    txtApellido.setText(medico.getApellido());
                    txtEdad.setText(medico.getEdad());
                    cmboSangre.setSelectedItem(medico.getTipoSangre());
                    txtTelefono.setText(medico.getTelefono());
                    txtEspecialidad.setText(medico.getEspecialidad());
                    cmboHorario.setSelectedItem(medico.getHorarioAtencion());

                } catch (Exception ex) {
                    
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "No existe esa identidad", "BUSCAR", JOptionPane.ERROR_MESSAGE);
                limpiar();
                
            }
        }

    }

    private void limpiar() {
        cmboIdentidad.setSelectedItem("SELECCIONE");
        txtIdentidad.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        txtEdad.setText("");
        cmboSangre.setSelectedItem("SELECCIONE");
        txtTelefono.setText("");
        txtEspecialidad.setText("");
        cmboHorario.setSelectedItem("SELECCIONE");
        cmboIdentidad.requestFocus();
    }
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmboHorario;
    private javax.swing.JComboBox<String> cmboIdentidad;
    private javax.swing.JComboBox<String> cmboSangre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMedicos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecialidad;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
