/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.citas;

import datos.*;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import logica.*;
import presentacion.citas.VerCitasApartadas;
import presentacion.paciente.RegistrarPaciente;

public class RegistrarCitas extends javax.swing.JDialog {

    DefaultComboBoxModel aModel = new DefaultComboBoxModel();
    Medico m = new Medico("", "");
    public RegistrarCitas(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();

    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        jLabelTipoIdentidad = new javax.swing.JLabel();
        cmbTipoIden = new javax.swing.JComboBox<>();
        jLabelIdentidad = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabelApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        cmbTipo = new javax.swing.JComboBox<>();
        verCitas = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR CITAS");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelNombre.setText("NOMBRE PACIENTE:");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(10, 50, 100, 30);

        txtNombreP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombrePKeyPressed(evt);
            }
        });
        getContentPane().add(txtNombreP);
        txtNombreP.setBounds(110, 50, 120, 30);

        jLabelTipoIdentidad.setText("TIPO IDENTDAD:");
        getContentPane().add(jLabelTipoIdentidad);
        jLabelTipoIdentidad.setBounds(10, 20, 110, 30);

        cmbTipoIden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "C.C", "T.I" }));
        getContentPane().add(cmbTipoIden);
        cmbTipoIden.setBounds(110, 20, 120, 30);

        jLabelIdentidad.setText("IDENTIDAD:");
        getContentPane().add(jLabelIdentidad);
        jLabelIdentidad.setBounds(290, 30, 80, 20);

        txtIdentidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdentidadKeyPressed(evt);
            }
        });
        getContentPane().add(txtIdentidad);
        txtIdentidad.setBounds(370, 20, 100, 30);

        jLabelApellido.setText("APELLIDO");
        getContentPane().add(jLabelApellido);
        jLabelApellido.setBounds(290, 60, 80, 20);

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtApellidoKeyPressed(evt);
            }
        });
        getContentPane().add(txtApellido);
        txtApellido.setBounds(370, 50, 100, 30);

        jLabel5.setText("FECHA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 80, 70, 30);

        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFechaKeyPressed(evt);
            }
        });
        getContentPane().add(txtFecha);
        txtFecha.setBounds(110, 80, 120, 30);

        jLabel6.setText("HORA:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 90, 60, 20);

        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtHoraKeyPressed(evt);
            }
        });
        getContentPane().add(txtHora);
        txtHora.setBounds(370, 80, 100, 30);

        jLabel7.setText("TIPO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 110, 60, 30);

        jLabel8.setText("DOCTOR:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 120, 60, 20);

        cmbDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDoctorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbDoctor);
        cmbDoctor.setBounds(370, 110, 100, 30);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar);
        btnRegistrar.setBounds(380, 170, 110, 30);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "GENERAL", "ESPECIALISTA" }));
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(110, 110, 120, 30);

        verCitas.setText("VER CITAS");
        verCitas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verCitasActionPerformed(evt);
            }
        });
        getContentPane().add(verCitas);
        verCitas.setBounds(500, 170, 100, 30);

        btnBuscar.setText("BUSCAR");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(270, 170, 100, 30);

        setSize(new java.awt.Dimension(641, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        registrar();
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if ((this.verificarmedico() == true) || (this.verificarPaciente()== true)) {
            JOptionPane.showMessageDialog(null, "No hay MEDICO ó PACIENTE registrados", "Registro de Citas", JOptionPane.ERROR_MESSAGE);
            this.dispose();
            RegistrarPaciente rp = new RegistrarPaciente(new javax.swing.JDialog(), true);
            rp.setVisible(true);
    }//GEN-LAST:event_formWindowOpened
    }
    private void verCitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verCitasActionPerformed
        VerCitasApartadas vca = new VerCitasApartadas(new javax.swing.JDialog(), true);
        vca.setVisible(true);
    }//GEN-LAST:event_verCitasActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscar();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtIdentidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentidadKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtIdentidadKeyPressed

    private void txtApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtApellidoKeyPressed

    private void txtNombrePKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombrePKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNombrePKeyPressed

    private void txtFechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyPressed
        if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtFechaKeyPressed

    private void txtHoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyPressed
       if (evt.isControlDown() || evt.isShiftDown()) {
            evt.consume();
        }
    }//GEN-LAST:event_txtHoraKeyPressed

    private void cmbDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDoctorActionPerformed
        JComboBox combo = (JComboBox) evt.getSource();
        m = (Medico) combo.getSelectedItem();
        llenarCombo();
    }//GEN-LAST:event_cmbDoctorActionPerformed
    
        public void llenarCombo() {
        for (Medico medico : ArchivoBinario.leerDatos() ) {
            Medico m1 = new Medico(medico.getNombre(), medico.getIdentidad());
            aModel.addElement(m1);
        }
    }
        public String getMedicName(String id) {
        for (Medico m : ArchivoBinario.leerDatos()) {
            if (m.getIdentidad().equals(id)) {
                return m.getNombre();
            }
        }
        return "";
    }
    private void buscar(){
                for (Paciente paciente : ArchivoBinario.leerDatosPa()) {
            if (txtIdentidad.getText().equals(paciente.getIdentidad())) {
                try {
                    cmbTipoIden.setSelectedItem(paciente.getTipoIdentidad());
                    txtIdentidad.setText(paciente.getIdentidad());
                    txtNombreP.setText(paciente.getNombre());
                    txtApellido.setText(paciente.getApellido());
                       

                } catch (Exception ex) {
                    
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "No existe esa identidad", "ERROR", JOptionPane.ERROR_MESSAGE);
                limpiar();
                
            }
        }
    
    }
    public boolean verificarmedico() {
        int cont = 0;
        for (Medico medico: ArchivoBinario.leerDatos()) {
            if (medico != null) {
                cont++;
            }
        }
        if (cont == 0) {
            return true;
        } else {
            return false; 
        }
    }
    
    public boolean verificarPaciente() {
        int cont = 0;
        for (Paciente paciente: ArchivoBinario.leerDatosPa()) {
            if (paciente != null) {
                cont++;
            }
        }
        if (cont == 0) {
            return true;
        } else {
            return false;
        }
    }
    private void registrar(){
        String mensaje;
        mensaje= Gestion.agregarCitas(cmbTipoIden.getSelectedItem().toString(), txtIdentidad.getText().trim(), txtNombreP.getText().trim(), txtApellido.getText().trim(),txtFecha.getText().trim(), txtHora.getText().trim(),cmbTipo.getSelectedItem().toString(), cmbDoctor.getSelectedItem().toString());
        JOptionPane.showMessageDialog(this, mensaje);
        limpiar();  

    }
    

   
    
    private void limpiar(){
        cmbTipoIden.setSelectedItem("SELECCIONE");
        txtIdentidad.setText("");
        txtNombreP.setText("");
        txtApellido.setText("");
        txtFecha.setText("");
        txtHora.setText("");
        cmbTipo.setSelectedItem("SELECCIONE");
        cmbDoctor.setSelectedItem("SELECCIONE");
        cmbTipoIden.requestFocus();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmbTipoIden;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelIdentidad;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoIdentidad;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JButton verCitas;
    // End of variables declaration//GEN-END:variables
}
