/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion.citas;

import javax.swing.JOptionPane;
import logica.Gestion;

/**
 *
 * @author JeanCarlos
 */
public class VerCitasApartadas extends javax.swing.JDialog {

  
    public VerCitasApartadas(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarDatos();
    }

    private void cargarDatos(){
        tblCitas.setModel(Gestion.getModeloTablaCitas());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblCitas = new javax.swing.JTable();
        btnCancelar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cmbTipoIden = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtIdentidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbDoctor = new javax.swing.JComboBox<>();
        cmbTipo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("VER CITAS"); // NOI18N
        setName("VER CITAS"); // NOI18N
        getContentPane().setLayout(null);

        tblCitas = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tblCitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblCitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblCitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblCitas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 230, 530, 190);

        btnCancelar.setText("CANCELAR");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar);
        btnCancelar.setBounds(310, 430, 97, 30);

        btnModificar.setText("MODIFICAR");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(420, 430, 103, 30);

        jLabel1.setText("NOMBRE PACIENTE:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 100, 30);
        getContentPane().add(txtNombreP);
        txtNombreP.setBounds(110, 50, 120, 30);

        jLabel2.setText("TIPO IDENTDAD:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 20, 110, 30);

        cmbTipoIden.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "C.C", "T.I" }));
        getContentPane().add(cmbTipoIden);
        cmbTipoIden.setBounds(110, 20, 120, 30);

        jLabel3.setText("IDENTIDAD:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 30, 80, 20);
        getContentPane().add(txtIdentidad);
        txtIdentidad.setBounds(370, 20, 100, 30);

        jLabel4.setText("APELLIDO");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 60, 80, 20);
        getContentPane().add(txtApellido);
        txtApellido.setBounds(370, 50, 100, 30);

        jLabel5.setText("FECHA:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 80, 70, 30);
        getContentPane().add(txtFecha);
        txtFecha.setBounds(110, 80, 120, 30);

        jLabel6.setText("HORA:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(290, 90, 60, 20);
        getContentPane().add(txtHora);
        txtHora.setBounds(370, 80, 100, 30);

        jLabel7.setText("TIPO:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 110, 60, 30);

        jLabel8.setText("DOCTOR:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(290, 120, 60, 20);

        cmbDoctor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "JEAN", "KIKI" }));
        getContentPane().add(cmbDoctor);
        cmbDoctor.setBounds(370, 110, 100, 30);

        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE", "GENERAL", "ESPECIALISTA" }));
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(110, 110, 120, 30);

        setSize(new java.awt.Dimension(563, 522));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelar();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        modificar();
    }//GEN-LAST:event_btnModificarActionPerformed

    private void tblCitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblCitasMouseClicked
        verDatos();
    }//GEN-LAST:event_tblCitasMouseClicked

    private void modificar(){
        Gestion.modificarCitas(cmbTipoIden.getSelectedItem().toString(), txtIdentidad.getText().trim(), txtNombreP.getText().trim(), txtApellido.getText().trim(),
        txtFecha.getText().trim(), txtHora.getText().trim(),cmbTipo.getSelectedItem().toString(), cmbDoctor.getSelectedItem().toString(),tblCitas.getSelectedRow());
        JOptionPane.showMessageDialog(this, "CITA MODIFICADA CORRECTAMENTE");
        limpiar();  
        cargarDatos();
    }
    
    private void cancelar(){
        Gestion.eliminarCitas(tblCitas.getSelectedRow());
        JOptionPane.showMessageDialog(this, "CITA CANCELADA CORRECTAMENTE");
        limpiar();
        cargarDatos();
    }
    
        private void verDatos(){
        cmbTipoIden.setSelectedItem(tblCitas.getValueAt(tblCitas.getSelectedRow(), 0).toString());
        txtIdentidad.setText(tblCitas.getValueAt(tblCitas.getSelectedRow(), 1).toString());
        txtNombreP.setText(tblCitas.getValueAt(tblCitas.getSelectedRow(), 2).toString());
        txtApellido.setText(tblCitas.getValueAt(tblCitas.getSelectedRow(), 3).toString());
        txtFecha.setText(tblCitas.getValueAt(tblCitas.getSelectedRow(), 4).toString());
        txtHora.setText(tblCitas.getValueAt(tblCitas.getSelectedRow(), 5).toString());
        cmbTipo.setSelectedItem(tblCitas.getValueAt(tblCitas.getSelectedRow(), 6).toString());
        cmbDoctor.setSelectedItem(tblCitas.getValueAt(tblCitas.getSelectedRow(), 7).toString());
        
        cmbTipoIden.requestFocus();
    }
        private void limpiar(){
        cmbTipoIden.setSelectedItem("SELECCIONE");
        txtIdentidad.setText("");
        txtNombreP.setText("");
        txtApellido.setText("");
        txtFecha.setText("");
        txtHora.setText("");
        cmbTipo.setSelectedItem("SELECCIONE");
        cmbDoctor.setSelectedItem("SELECCIONE");
        cmbTipoIden.requestFocus();
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cmbDoctor;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JComboBox<String> cmbTipoIden;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCitas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtIdentidad;
    private javax.swing.JTextField txtNombreP;
    // End of variables declaration//GEN-END:variables
}
