package proyectofinal;

import archivos.ManejoBinario;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistrarVentas extends javax.swing.JDialog {

    Producto producto;
    Persona persona;

    ArrayList<Producto> listaVentas;
    DefaultTableModel modelo;

    public RegistrarVentas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cambiarIcono();
        listaVentas = new ArrayList<>();
        cargarDatosArchivo();
        //pintarTabla();
    }

    private void cambiarIcono() {
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconcono.png")).getImage());
    }

    private void cargarDatosArchivo() {
        listaVentas = ManejoBinario.leerBinarioVentas();
//        pintarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTablaVentas = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        id = new javax.swing.JLabel();
        nombre = new javax.swing.JLabel();
        cargo = new javax.swing.JLabel();
        idTexto = new javax.swing.JTextField();
        nombreTexto = new javax.swing.JTextField();
        cargoCombo = new javax.swing.JComboBox<>();
        agregar = new javax.swing.JButton();
        sisben = new javax.swing.JLabel();
        sisbenTexto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Heladería - Registrar Ventas");

        jPanel1.setBackground(new java.awt.Color(92, 216, 222));

        listaTablaVentas.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        listaTablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listaTablaVentas.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(listaTablaVentas);

        salir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        id.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        id.setText("Identificación");

        nombre.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        nombre.setText("Nombre");

        cargo.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        cargo.setText("Cargo");

        idTexto.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        idTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idTextoKeyTyped(evt);
            }
        });

        nombreTexto.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        nombreTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreTextoKeyTyped(evt);
            }
        });

        cargoCombo.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        cargoCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estudiante", "Docente", "Funcionario", "Particular" }));
        cargoCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargoComboActionPerformed(evt);
            }
        });

        agregar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar pequeño.png"))); // NOI18N
        agregar.setBorder(null);
        agregar.setBorderPainted(false);
        agregar.setContentAreaFilled(false);
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        sisben.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        sisben.setText("Sisben");

        sisbenTexto.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        sisbenTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sisbenTextoKeyTyped(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo mini.png"))); // NOI18N

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar pequeño.png"))); // NOI18N
        guardar.setBorder(null);
        guardar.setBorderPainted(false);
        guardar.setContentAreaFilled(false);
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombre)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(id)
                                    .addComponent(cargo)
                                    .addComponent(sisben))
                                .addGap(40, 40, 40)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(agregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(idTexto)
                                    .addComponent(nombreTexto)
                                    .addComponent(cargoCombo, 0, 179, Short.MAX_VALUE)
                                    .addComponent(sisbenTexto))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id)
                            .addComponent(idTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre)
                            .addComponent(nombreTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cargo)
                            .addComponent(cargoCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sisben)
                            .addComponent(sisbenTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Heladeria heladeria = new Heladeria();
        heladeria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void cargoComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargoComboActionPerformed
        if (cargoCombo.getSelectedItem().equals("Estudiante")) {
            sisbenTexto.setEditable(true);
            sisbenTexto.setEnabled(true);
            sisbenTexto.setVisible(true);
            sisben.setVisible(true);
        }

        if (cargoCombo.getSelectedItem().equals("Docente")) {
            sisbenTexto.setEditable(false);
            sisbenTexto.setEnabled(false);
            sisbenTexto.setVisible(false);
            sisben.setVisible(false);
        }

        if (cargoCombo.getSelectedItem().equals("Funcionario")) {
            sisbenTexto.setEditable(false);
            sisbenTexto.setEnabled(false);
            sisbenTexto.setVisible(false);
            sisben.setVisible(false);
        }

        if (cargoCombo.getSelectedItem().equals("Particular")) {
            sisbenTexto.setEditable(false);
            sisbenTexto.setEnabled(false);
            sisbenTexto.setVisible(false);
            sisben.setVisible(false);
        }
    }//GEN-LAST:event_cargoComboActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        ManejoBinario.guardarBinarioVentas(listaVentas);
    }//GEN-LAST:event_guardarActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
//        agregar();
    }//GEN-LAST:event_agregarActionPerformed

    private void nombreTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreTextoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isDigit(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar letras");
        }
    }//GEN-LAST:event_nombreTextoKeyTyped

    private void idTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTextoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar numeros");
        }
    }//GEN-LAST:event_idTextoKeyTyped

    private void sisbenTextoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sisbenTextoKeyTyped
        char validar = evt.getKeyChar();
        if (Character.isLetter(validar)) {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Solo se permite ingresar numeros");
        }
    }//GEN-LAST:event_sisbenTextoKeyTyped

//    private void agregar() {
//        try {
//            String Id, Nombre, Cargo, Producto, Tipo;
//            double Sisben = 0, Tarifa;
//            int Cantidad;
//
//            Id = idTexto.getText().trim();
//            Nombre = nombreTexto.getText().trim();
//            Cargo = cargoCombo.getSelectedItem().toString().trim();
//            Tipo = tipoHeladoCombo.getSelectedItem().toString().trim();
//
//            if (cargoCombo.getSelectedItem().equals("Estudiante")) {
//                Sisben = Double.parseDouble(sisbenTexto.getText().trim());
//            }
//            Tipo = tipoHeladoCombo.getSelectedItem().toString().trim();
//            Producto=tipoProducto.getText();
//            Cantidad = Integer.parseInt(cantidadTexto.getText().trim());
//
////            if (validarTabla(Id)) {
//                JOptionPane.showMessageDialog(rootPane, "La ID ingresada ya existe", "Advertencia", JOptionPane.ERROR_MESSAGE);
//            } else {
//                producto = new Producto();
//                persona = new Persona();
//                persona.setId(Id);
//                producto.setId(persona.getId());
//                producto.setNombre(Nombre);
//                producto.setTipoPersona(Cargo);
//                producto.setSisben(Sisben);
                //producto.setTipoProducto(Producto);
//                producto.setCantidad(Cantidad);

//
//                if (cargoCombo.getSelectedItem().equals("Estudiante")) {
//                    if (idTexto.getText().equals("") || nombreTexto.getText().equals("") || sisbenTexto.getText().equals("") || cantidadTexto.getText().equals("")) {
//                        JOptionPane.showMessageDialog(rootPane, "Llene todos los campos", "Mensaje", JOptionPane.ERROR_MESSAGE);
//                    } else {
//                        listaVentas.add(producto);
//                        limpiar();
//                        pintarTabla();
//                    }
//                } else {
//                    if (idTexto.getText().equals("") || nombreTexto.getText().equals("") || cantidadTexto.getText().equals("")) {
//                        JOptionPane.showMessageDialog(rootPane, "Llene todos los campos", "Mensaje", JOptionPane.ERROR_MESSAGE);
//                    } else {
//                        listaVentas.add(producto);
//                        limpiar();
//                        pintarTabla();
//                    }
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Llene todos los campos", "Mensaje", JOptionPane.ERROR_MESSAGE);
//        }
//
//    }
//
//    private void limpiar() {
//        idTexto.setText("");
//        nombreTexto.setText("");
//        cargoCombo.setSelectedItem("Estudiante");
//        tipoHeladoCombo.setSelectedItem("---------------------------");
//        sisbenTexto.setText("");
//        cantidadTexto.setText("");
//        idTexto.requestFocus();
//    }
//
//    private void pintarTabla() {
//        modelo = new DefaultTableModel();
//        String[] nombreColumnas = {"Identidad", "Nombre", "Cargo", "Sisben", "Producto", "Cantidad", "Tarifa"};
//        modelo.setColumnIdentifiers(nombreColumnas);
//        for (Producto p1 : listaVentas) {
//            String[] fila = {p1.getId(), p1.getNombre(), p1.getTipoPersona(), String.valueOf(p1.getSisben()), p1.getTipoProducto(), String.valueOf(p1.getCantidad()), String.valueOf(p1.getTarifa())};
//            modelo.addRow(fila);
//        }
//        listaTablaVentas.setModel(modelo);
//    }

//    private boolean validarTabla(String Id) {
//        for (Producto p2 : listaVentas) {
//            if (p2.getId().equals(Id)) {
//                return true;
//            }
//        }
//        return false;
//    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarVentas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarVentas dialog = new RegistrarVentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JLabel cargo;
    private javax.swing.JComboBox<String> cargoCombo;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel id;
    private javax.swing.JTextField idTexto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaTablaVentas;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField nombreTexto;
    private javax.swing.JButton salir;
    private javax.swing.JLabel sisben;
    private javax.swing.JTextField sisbenTexto;
    // End of variables declaration//GEN-END:variables
}
