package proyectofinal;

import archivos.ManejoBinario;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class RegistrarCompras extends javax.swing.JDialog {

    Producto producto;
    ArrayList<Producto> listaCompras;
    DefaultTableModel modelo;

    public RegistrarCompras(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cambiarIcono();
        listaCompras = new ArrayList<>();
        cargarDatosArchivo();
        pintarTabla();
    }

    private void cambiarIcono() {
        this.setIconImage(new ImageIcon(getClass().getResource("/imagenes/iconcono.png")).getImage());
    }

    private void cargarDatosArchivo() {
        listaCompras = ManejoBinario.leerBinarioCompras();
        pintarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaTablaCompras = new javax.swing.JTable();
        salir = new javax.swing.JButton();
        agregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        guardar = new javax.swing.JButton();
        chococonoTexto1 = new javax.swing.JTextField();
        paletaTexto1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        comboTipoH = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nombreHeladoTexto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cantidadHeladoTexto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        valorHeladoTexto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Heladería - Registrar Compras");

        jPanel1.setBackground(new java.awt.Color(92, 216, 222));

        listaTablaCompras.setFont(new java.awt.Font("Roboto Cn", 0, 12)); // NOI18N
        listaTablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listaTablaCompras.setGridColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(listaTablaCompras);

        salir.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        salir.setBorder(null);
        salir.setBorderPainted(false);
        salir.setContentAreaFilled(false);
        salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        agregar.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/agregar pequeño.png"))); // NOI18N
        agregar.setBorder(null);
        agregar.setBorderPainted(false);
        agregar.setContentAreaFilled(false);
        agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo mini.png"))); // NOI18N

        guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/guardar pequeño.png"))); // NOI18N
        guardar.setBorder(null);
        guardar.setBorderPainted(false);
        guardar.setContentAreaFilled(false);
        guardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        chococonoTexto1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        chococonoTexto1.setBorder(null);

        paletaTexto1.setFont(new java.awt.Font("Roboto Cn", 0, 14)); // NOI18N
        paletaTexto1.setBorder(null);

        jLabel15.setText("TIPO DE HELADO");

        comboTipoH.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TRADICIONAL SERVIDO", "TRADICIONAL PRE-SERVIDO", "ESPECIAL SERVIDO", " " }));

        jLabel2.setText("NOMBRE");

        nombreHeladoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreHeladoTextoActionPerformed(evt);
            }
        });

        jLabel3.setText("CANTIDAD");

        cantidadHeladoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cantidadHeladoTextoActionPerformed(evt);
            }
        });

        jLabel4.setText("VALOR");

        valorHeladoTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorHeladoTextoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboTipoH, 0, 177, Short.MAX_VALUE)
                                            .addComponent(nombreHeladoTexto)
                                            .addComponent(cantidadHeladoTexto)
                                            .addComponent(valorHeladoTexto)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(123, 123, 123)
                                        .addComponent(agregar)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(110, 110, 110)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(chococonoTexto1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paletaTexto1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addContainerGap(389, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(comboTipoH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(nombreHeladoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(cantidadHeladoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(valorHeladoTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(salir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(chococonoTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(paletaTexto1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(198, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        Heladeria heladeria = new Heladeria();
        heladeria.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_salirActionPerformed

    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        agregar();
    }//GEN-LAST:event_agregarActionPerformed

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        ManejoBinario.guardarBinarioCompras(listaCompras);
    }//GEN-LAST:event_guardarActionPerformed

    private void nombreHeladoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreHeladoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreHeladoTextoActionPerformed

    private void cantidadHeladoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cantidadHeladoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cantidadHeladoTextoActionPerformed

    private void valorHeladoTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorHeladoTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valorHeladoTextoActionPerformed

    private void agregar() {
        try {
            int Cantidad;
            double Valor;
            String TipoHelado,Nombre;

            TipoHelado = comboTipoH.getSelectedItem().toString().trim();
            Cantidad = Integer.parseInt(cantidadHeladoTexto.getText().trim());
            Nombre = nombreHeladoTexto.getText().trim();
            Valor = Double.parseDouble(valorHeladoTexto.getText().trim());

            producto = new Producto();
            producto.setTipoProducto(TipoHelado);
            producto.setCantidad(Cantidad);
            producto.setTarifa(Valor);
            producto.setNombreProducto(Nombre);
            listaCompras.add(producto);
            limpiar();
            pintarTabla();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Llene todos los campos", "Mensaje", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void limpiar() {
        cantidadHeladoTexto.setText("");
        nombreHeladoTexto.setText("");
        valorHeladoTexto.setText("");
        comboTipoH.setSelectedItem("TRADICIONAL SERVIDO");

        comboTipoH.requestFocus();
    }

    private void pintarTabla() {
        modelo = new DefaultTableModel();
        String[] nombreColumnas = {"TIPO DE HELADO", "NOMBRE", "CANTIDAD", "VALOR"};
        modelo.setColumnIdentifiers(nombreColumnas);
        for (Producto p1 : listaCompras) {
            String[] fila = {p1.getTipoProducto(),p1.getNombreProducto().toUpperCase(), String.valueOf(p1.getCantidad()), String.valueOf(p1.getTarifa())};
            modelo.addRow(fila);
        }
        listaTablaCompras.setModel(modelo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RegistrarCompras dialog = new RegistrarCompras(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregar;
    private javax.swing.JTextField cantidadHeladoTexto;
    private javax.swing.JTextField chococonoTexto1;
    private javax.swing.JComboBox<String> comboTipoH;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listaTablaCompras;
    private javax.swing.JTextField nombreHeladoTexto;
    private javax.swing.JTextField paletaTexto1;
    private javax.swing.JButton salir;
    private javax.swing.JTextField valorHeladoTexto;
    // End of variables declaration//GEN-END:variables
}
