/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;


import presentacion.citas.*;
import presentacion.medico.*;
import presentacion.paciente.*;

/**
 *
 * @author JeanCarlos
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        mGestion = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        Medicos = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        registroPaciente = new javax.swing.JMenuItem();
        Citas = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        consultaMedico = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GESTION HOSPITALARIA");
        getContentPane().setLayout(null);

        mGestion.setText("GESTION");

        jMenu3.setText("REGISTRAR");

        Medicos.setText("MEDICO");
        Medicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicosActionPerformed(evt);
            }
        });
        jMenu3.add(Medicos);

        jMenu1.setText("PACIENTES");

        registroPaciente.setText("REGISTRAR PACIENTE");
        registroPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroPacienteActionPerformed(evt);
            }
        });
        jMenu1.add(registroPaciente);

        Citas.setText("CITAS");
        Citas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitasActionPerformed(evt);
            }
        });
        jMenu1.add(Citas);

        jMenuItem1.setText("VER CITAS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenu3.add(jMenu1);

        jMenuItem2.setText("GESTION MEDICAMENTOS");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        mGestion.add(jMenu3);

        jMenu4.setText("CONSULTAS");

        consultaMedico.setText("MEDICO");
        consultaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultaMedicoActionPerformed(evt);
            }
        });
        jMenu4.add(consultaMedico);

        jMenuItem3.setText("PACIENTES");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem4.setText("CITAS");
        jMenu4.add(jMenuItem4);

        mGestion.add(jMenu4);

        jMenuBar1.add(mGestion);

        jMenu2.setText("SALIR");

        jMenuItem5.setText("SALIR");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(542, 390));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registroPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroPacienteActionPerformed
        RegistrarPaciente rp = new RegistrarPaciente(new javax.swing.JDialog(), true);
        rp.setVisible(true);
    }//GEN-LAST:event_registroPacienteActionPerformed

    private void MedicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicosActionPerformed
        RegistrarMedico rm = new RegistrarMedico(new javax.swing.JDialog(), true);
        rm.setVisible(true);
    }//GEN-LAST:event_MedicosActionPerformed

    private void CitasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitasActionPerformed
       RegistrarCitas rc = new RegistrarCitas(new javax.swing.JDialog(), true);
       rc.setVisible(true);
    }//GEN-LAST:event_CitasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       VerCitasApartadas vca = new VerCitasApartadas(new javax.swing.JDialog(), true);
       vca.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
       GestionMedicamento gm = new GestionMedicamento(new javax.swing.JDialog(), true);
       gm.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void consultaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultaMedicoActionPerformed
        VerMedicos vm = new VerMedicos(new javax.swing.JDialog(), true);
        vm.setVisible(true);
    }//GEN-LAST:event_consultaMedicoActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        VerPacientes vp = new VerPacientes(new javax.swing.JDialog(), true);
        vp.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
       System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
      }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Citas;
    private javax.swing.JMenuItem Medicos;
    private javax.swing.JMenuItem consultaMedico;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenu mGestion;
    private javax.swing.JMenuItem registroPaciente;
    // End of variables declaration//GEN-END:variables
}
